spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.mydocent.docent.config.SnakeCaseNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


perplexity:
  api-key: ${PERPLEXITY_API_KEY}